plugins { id 'com.android.application' }
android {
    namespace 'com.levi.dialog'
    compileSdk 34
    defaultConfig {
        applicationId 'com.levi.dialog'
        minSdk 21
        targetSdk 34
        versionCode 3
        versionName '2.0.0'
        multiDexEnabled false
    }
    buildTypes { release { minifyEnabled false; signingConfig signingConfigs.debug } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
